DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS config;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE config (
  key TEXT NOT NULL,
  type TEXT NOT NULL,
  value TEXT NOT NULL
);
